=== Mcfell/SpringSimple/target/classes/personSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns="http://www.w3school.com.cn"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3school.com.cn"
elementFormDefault="qualified">

<!-- xmlns:xs						显示 schema 中用到的元素和数据类型来自命名空间 "http://www.w3.org/2001/XMLSchema"。同时它还规定了来自命名空间 "http://www.w3.org/2001/XMLSchema" 的元素和数据类型应该使用前缀 xs：
	 targetNamespace  				显示被此 schema 定义的元素 (note, to, from, heading, body) 来自命名空间： "http://www.w3school.com.cn" 
	 xmlns  						指出默认的命名空间是 "http://www.w3school.com.cn"
	 elementFormDefault="qualified" 指出任何 XML 实例文档所使用的且在此 schema 中声明过的元素必须被命名空间限定-->
<!-- 使用指定的类型 -->
<xsd:simpleType name="stringtype">
 <xsd:restriction base="xs:string">
 	<xsd:enumeration value="Audi" />
    <xsd:enumeration value="Golf" />
    <xsd:enumeration value="BMW" />
 </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="inttype">
 <xsd:restriction base="xs:positiveInteger">
 	<xsd:minInclusive value="1" />
    <xsd:maxInclusive value="120" />
 </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="dectype">
 <xsd:restriction base="xs:decimal" />
</xsd:simpleType>

<xsd:simpleType name="orderidtype">
 <xsd:restriction base="xs:string">
  <xsd:pattern value="[0-9]{6}" />
 </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="whiteSpace">
  <xsd:restriction base="xs:string">
    <xsd:whiteSpace value="preserve" />
  </xsd:restriction>
</xsd:simpleType>

<!-- 简易元素的定义 -->
<xsd:element name="orderperson" type="xs:string" />
<xsd:element name="name" type="xs:string" />
<xsd:element name="address" type="xs:string" />
<xsd:element name="city" type="xs:string" default="beijing" />
<xsd:element name="country" type="xs:string" fixed="china" />
<xsd:element name="title" type="xs:string" />
<xsd:element name="note" type="xs:string" />
<xsd:element name="quantity" type="xs:positiveInteger" />
<xsd:element name="price" type="xs:decimal" />

<!-- 属性的定义 -->
<!-- 简易元素无法拥有属性。假如某个元素拥有属性，它就会被当作某种复合类型。但是属性本身总是作为简易类型被声明的。
	最常用的类型是:
	xs:string
	xs:decimal
	xs:integer
	xs:boolean
	xs:date
	xs:time 
	在缺省的情况下，属性是可选的。如需规定属性为必选，请使用 "use" 属性：
	<xs:attribute name="lang" type="xs:string" use="required"/>-->
<xsd:attribute name="orderid" type="xs:string" />

<!-- 复合元素的定义 -->
<xsd:element name="shipto">
 
        <xsd:complexType>
  <xsd:sequence>
   <xsd:element ref="name" />
   <xsd:element ref="address" />
   <xsd:element ref="city" />
   <xsd:element ref="country" />
  </xsd:sequence>
  <xsd:attribute name="orderid" type="xs:string" />
 </xsd:complexType>
    </xsd:element>
<xsd:element name="item">
 
        <xsd:complexType>
  <xsd:sequence>
   <xsd:element ref="title" />
   <xsd:element ref="note" minOccurs="0" />
   <xsd:element ref="quantity" />
   <xsd:element ref="price" />
  </xsd:sequence>
 </xsd:complexType>
    </xsd:element>

<xsd:element name="shiporder">
 
        <xsd:complexType>
  <xsd:sequence>
   <xsd:element ref="orderperson" />
   <xsd:element ref="shipto" />
   <xsd:element ref="item" maxOccurs="unbounded" />
  </xsd:sequence>
  <xsd:attribute ref="orderid" use="required" />
 </xsd:complexType>
    </xsd:element>

<xsd:element name="employee" type="personinfo" />
<xsd:element name="student" type="personinfo" />
<xsd:element name="member" type="personinfo" />
<xsd:element name="fullmember" type="fullpersoninfo" />

<xsd:complexType name="personinfo">
  <xsd:sequence>
    <xsd:element name="firstname" type="xs:string" />
    <xsd:element name="lastname" type="xs:string" />
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="fullpersoninfo">
  <xsd:complexContent>
    <xsd:extension base="personinfo">
      <xsd:sequence>
        <xsd:element name="address" type="xs:string" />
        <xsd:element name="city" type="xs:string" />
        <xsd:element name="country" type="xs:string" />
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:import namespace="http://www.springframework.org/schema/beans" />

 <xsd:element name="datasource">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:extension base="beans:identifiedType">
          <xsd:attribute name="url" type="xsd:string" use="required" />
          <xsd:attribute name="userName" type="xsd:string" use="required" />
          <xsd:attribute name="password" type="xsd:string" use="required" />
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>
<xsd:schema></xsd:schema>

=== Mcfell/SpringSimple/target/classes/shiporder.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<shiporder orderid="889923"
xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:noNamespaceSchemaLocation="personSchema.xsd">
 <orderperson>George Bush</orderperson>
 <item>
  <title>Empire Burlesque</title>
  <note>Special Edition</note>
  <quantity>1</quantity>
  <price>10.90</price>
 </item>
 <item>
  <title>Hide your heart</title>
  <quantity>1</quantity>
  <price>9.90</price>
 </item>
</shiporder>
